# Generated by Django 5.1 on 2025-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('ropa', 'Ropa'), ('accesorios', 'Accesorios'), ('zapatos', 'Zapatos'), ('belleza', 'Belleza'), ('hogar', 'Hogar')], max_length=20)),
                ('talla', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('Única', 'Única')], max_length=10, null=True)),
                ('color', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('imagen_url', models.URLField(blank=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='cliente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
